# This file was generated by GoReleaser. DO NOT EDIT.
cask "curious" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "dfdb5b6e674b6b3de3f22d8ca6d5b5600bb13293b16447b98dcbcb021188461d"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f58f0188f4ccabd54b617f3104f2beb6e6bb0e3a77148dcc01f2a9fe2c44956a"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "54c184fc42cba537fded30c403f480a11203c0ebee5b15dd2e0f9991f015f31c"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cd9638a6dbda99ddde62080de09e87960928478c28183b2c093befedf58bf07b"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_linux_amd64.tar.gz"
    end
  end

  name "curious"
  desc "Pack an Astro project, upload it, and stream the build"
  homepage "https://curious.pub/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "curious"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/curious"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask is deprecated and is removed in the next release.
    Install the formula instead, which also works on Linux:
      brew uninstall --cask curious && brew install curiouspub/tap/curiouspub
    If the formula is already installed, it was not linked while this
    cask held the curious command. Remove the cask, then link it:
      brew uninstall --cask curious && brew link curiouspub/tap/curiouspub
  EOS
end
