# This file was generated by GoReleaser. DO NOT EDIT.
cask "curious" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "309d03312e54a43cab604fdb9f17f622479d77137eb00805cb4c256145e33f7e"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf8493eb7dcd6e3c9f5c012d8fe1cc59c7d26621939063b2ecf76a71d1fcde1c"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7accbf334876b3814181484302ba2bd0f7ada2b9d69a78e291fbf710567c60ef"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "df6bffb9f7307ae2a7f16c7c17d2588d582a35427d233de2fe5b2c975051fb14"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_linux_amd64.tar.gz"
    end
  end

  name "curious"
  desc "Pack an Astro project, upload it, and stream the build"
  homepage "https://curious.pub/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "curious"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/curious"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask is deprecated and is removed in the next release.
    Install the formula instead, which also works on Linux:
      brew uninstall --cask curious
      brew install curiouspub/tap/curiouspub
  EOS
end
