# This file was generated by GoReleaser. DO NOT EDIT.
cask "curious" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9779617b38f36237d0db45bba189a32e1cb2a5d9b9105115ff8a456aca9b85d2"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cdd610ca1ab4ef1ac2e731adaf3cdc4d270ea92593a6fa2d2bfe82923ef8390"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ebaffd03c8dc673fb6807f32a5f54ae1c9e02e4a9f02f14a428865c20877162"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "84bc57559705b47e65ef94e668d11ef2b4149b3e71a15160ce8e144fe7fc7003"
      url "https://github.com/curiouspub/cli/releases/download/v#{version}/curious_#{version}_linux_amd64.tar.gz"
    end
  end

  name "curious"
  desc "Pack an Astro project, upload it, and stream the build."
  homepage "https://curious.pub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "curious"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/curious"]
    end
  end

  # No zap stanza required
end
